### ISSUE TITLE
Mode selector has no effect

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analyst-server#104]
I always get walk to transi results, even when I select walk-only.

**Comment by mattwigway** [comment]
Ah. We need to deselect profile routing and toggle automatically over to 'estimated accessibility'.

**Comment by knaaptime** [comment]
possibly related -- I get errors when trying to do a regional analysis with non-transit modes 

```
[info] application - created query q 7601d1a40eb4c616d06281b1a2a27fdd
[info] application - saved query q 7601d1a40eb4c616d06281b1a2a27fdd
akka://analyst-server/user/$d
[ERROR] [05/18/2015 21:16:53.788] [analyst-server-akka.actor.default-dispatcher-5] [akka://analyst-server/user/$d] null
java.lang.NullPointerException
        at models.Query$QueryActor.onReceive(Query.java:277)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[info] application - saved query q 7601d1a40eb4c616d06281b1a2a27fdd
get status: 0 requests outstanding, 10 chunk size

```

single point queries still work with the same parameters

**Comment by mattwigway** [comment]
@knaaptime thanks for the report - I believe that is a separate issue. Please feel free to open a new ticket.
