### ISSUE TITLE
Non-fatal exception at startup

### ISSUE THREAD

**Issue by abyrd** [conveyal/analyst-server#107]
This seems to happen every time I start up analyst-server, but the program continues to function:

```
java.lang.ArrayIndexOutOfBoundsException: 16152
	at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:174)
	at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:153)
	at com.avaje.ebean.enhance.agent.Transformer.detect(Transformer.java:251)
	at com.avaje.ebean.enhance.agent.Transformer.transform(Transformer.java:106)
	at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:55)
	at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:39)
	at com.avaje.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:141)
	at com.avaje.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
	at com.avaje.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:90)
	at play.PlayCommands$$anonfun$PostCompile$1.apply(PlayCommands.scala:142)
	at play.PlayCommands$$anonfun$PostCompile$1.apply(PlayCommands.scala:75)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattwigway** [comment]
This has to with some sort of bug in Play's ebean class enhancer, which we don't use. I'll just turn it off.
