### ISSUE TITLE
Running a local Vanilla-Extract server

### ISSUE THREAD

**Issue by radumas** [conveyal/analyst-server#117]
From the analyst server README it was not obvious to me how to properly configure a local vex server to run analyst-server. From the error I got when trying to process GTFS data, I'm assuming that analyst-server is trying to access a URL, not the local `./vex` command. Do I therefore need to be running the vex.js using Node?
```
java.net.MalformedURLException: no protocol: ~/vanilla-extract/vex/41.581289,-71.794888,42.797837,-70.627055.pbf
        at java.net.URL.<init>(URL.java:586)
        at java.net.URL.<init>(URL.java:483)
        at java.net.URL.<init>(URL.java:432)
        at jobs.ProcessTransitBundleJob.run(ProcessTransitBundleJob.java:179)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Failed to process gtfs
[info] application - saved bundle 4ec302ae4d627c8b8305387f13a3b3b3
```

**Comment by mattwigway** [comment]
Yes, that's correct, analyst-server only supports fetching Vex data from a URL. We're not using the node.js vex implementation anymore, but rather the vex server that is built into [osm-lib](http://github.com/conveyal/osm-lib). OSM-lib has numerous advantages, chief among them that it can consume minutely updates and be perpetually in sync with the OSM master database. I need to write up some documentation on configuring OSM-lib as a vex server.
