### ISSUE TITLE
Error in SQS lib when saving work stats

### ISSUE THREAD

**Issue by abyrd** [conveyal/analyst-server#164]
```
15:11:50.267 ERROR (SQSTaskStatisticsStore.java:54) Error saving stats to SQS
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.amazonaws.services.sqs.QueueUrlHandler.beforeRequest(QueueUrlHandler.java:39) ~[aws-java-sdk-sqs-1.10.10.jar:na]
	at com.amazonaws.handlers.RequestHandler2Adaptor.beforeRequest(RequestHandler2Adaptor.java:37) ~[aws-java-sdk-core-1.9.39.jar:na]
	at com.amazonaws.http.AmazonHttpClient.requestHandler2s(AmazonHttpClient.java:405) ~[aws-java-sdk-core-1.9.39.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:283) ~[aws-java-sdk-core-1.9.39.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2419) ~[aws-java-sdk-sqs-1.10.10.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessageBatch(AmazonSQSClient.java:783) ~[aws-java-sdk-sqs-1.10.10.jar:na]
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$SendMessageBatchTask.process(SendQueueBuffer.java:510) ~[aws-java-sdk-sqs-1.10.10.jar:na]
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$OutboundBatchTask.run(SendQueueBuffer.java:441) ~[aws-java-sdk-sqs-1.10.10.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
```

**Comment by mattwigway** [comment]
This is actually an issue in the latest version of the AWS Java SDK. If we revert to the previous version, we don't have support for m4.xlarge instances that we use as workers.
