### ISSUE TITLE
Alpha out of range error

### ISSUE THREAD

**Issue by abyrd** [conveyal/analyst-server#165]
```
15:18:45.752 [qtp717412413-42] INFO  com.conveyal.analyst.server.Routes - unhandled exception, caught by server thread
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Color parameter outside of expected range: Alpha
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
	at com.conveyal.analyst.server.tiles.TileCache.get(TileCache.java:26) ~[classes/:na]
	at com.conveyal.analyst.server.controllers.Tiles.tileBuilder(Tiles.java:30) ~[classes/:na]
	at com.conveyal.analyst.server.controllers.Tiles.shape(Tiles.java:132) ~[classes/:na]
	at com.conveyal.analyst.server.Routes$$Lambda$57/1484275564.handle(Unknown Source) ~[na:na]
	at spark.SparkBase$1.handle(SparkBase.java:311) ~[spark-core-2.2.jar:na]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159) ~[spark-core-2.2.jar:na]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60) [spark-core-2.2.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.Server.handle(Server.java:451) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240) [jetty-io-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596) [jetty-util-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527) [jetty-util-9.0.2.v20130417.jar:9.0.2.v20130417]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

```

**Comment by mattwigway** [comment]
Do we know what this was in relation to? What kind of tiles were you trying to render?

I don't think this is the full stack trace. There should be a Caused by java.lang.IllegalArgumentException below that will show where the issue actually is.
