### ISSUE TITLE
Cannot saved changed name after creating scenario

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analyst-server#45]
If I create a scenario, wait for it to build and then change the name, I can't save it. I suspect this is because a property "status" gets set during graph building, which the server chokes on on save:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "status" (class models.Scenario), not marked as ignorable (9 known properties: "name", "processingGtfs", "projectId", "bounds", "processingOsm", "files", "id", "description", "failed"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: models.Scenario["status"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:731)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:915)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:243)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3023)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1637)
	at controllers.Api.updateScenario(Api.java:751)
```

**Comment by mattwigway** [comment]
Fixed in master, evidently.
