### ISSUE TITLE
Cannot delete and then reupload same shapefile

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analyst-server#52]
I get this when I try:

    java.lang.IllegalArgumentException: Name already used:        669a0f471667f47b1bf7c1ccba0cda4e_88592d59a5506d36a06d42315cca6b82
	at org.mapdb.DB.checkNameNotExists(DB.java:1544) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.DB.createTreeMap(DB.java:817) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.DB$BTreeMapMaker.make(DB.java:644) ~[mapdb-1.0.6.jar:na]
	at utils.DataStore.<init>(DataStore.java:91) ~[na:na]
	at models.Shapefile.setShapeFeatureStore(Shapefile.java:314) ~[na:na]

**Comment by mattwigway** [comment]
Bump. still an issue.

**Comment by mattwigway** [comment]
Fixed. We don't use hashes anymore.
