### ISSUE TITLE
S3 access errors 

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analyst-server#60]
This is only happening locally, so it may be an s3 misconfiguration, but I'm getting permission denied when trying to get pointsets from S3 in the executive; it works fine on the workers, which use the same s3 config. `rm -rf cache` fixes.

**Comment by mattwigway** [comment]
```
com.google.common.util.concurrent.UncheckedExecutionException: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9A36D1250475D477), S3 Extended Request ID: iJuPv+gJgXAyRD2pMtPxVJZgIyKYPWxJop40B7rr8486CFUnqZYVfxE/FJV5TtMgjtC9+8vwZMk=
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at org.opentripplanner.analyst.PointSetCache.get(PointSetCache.java:26)
	at com.conveyal.otpac.message.JobSpec.buildPointSet(JobSpec.java:112)
	at com.conveyal.otpac.message.JobSpec.getOrigins(JobSpec.java:102)
	at com.conveyal.otpac.actors.Executive.onMsgJobSpec(Executive.java:407)
	at com.conveyal.otpac.actors.Executive.onReceive(Executive.java:150)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9A36D1250475D477), S3 Extended Request ID: iJuPv+gJgXAyRD2pMtPxVJZgIyKYPWxJop40B7rr8486CFUnqZYVfxE/FJV5TtMgjtC9+8vwZMk=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:820)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:439)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:245)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3722)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1137)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1002)
	at com.conveyal.otpac.PointSetDatastore$S3PointSetLoader.load(PointSetDatastore.java:122)
	at com.conveyal.otpac.PointSetDatastore$S3PointSetLoader.load(PointSetDatastore.java:98)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 21 more
```

**Comment by mattwigway** [comment]
Now seeing on the workers as well.

**Comment by mattwigway** [comment]
I found a quite-likely-related bug: if you upload a shapefile, it doesn't always get written to cluster cache, even locally, which would cause this error (not able to find locally, ask S3, S3 has list permission off so says permission denied not doesn't exist).

**Comment by mattwigway** [comment]
Ah, I think I've found the issue. On application startup, things get written to S3 asynchronously. Some of these files are huge, so this can take a while. If you start analysis before the relevant pointset is written to cluster cache, you get this error.

**Comment by mattwigway** [comment]
OK, so two-pronged approach:

- Write to S3 synchronously
- Write gzipped files in to S3.
